### PR TITLE
chore: Updated lint-staged config

### PR DESCRIPTION
**Pull request by jamesgeorge007**
- Included `lint:fix` script to autofix lint issues.
- Updated `lint-staged` config to autofix lint issues and stage the respective files.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
In-fact this is most commonly followed approach. Auto-fixing and staging the respective files is gonna add to the DX rather than leaving it off to him/her, just my honest opinion.

**Comment by jperl** [comment]
Ok you convinced me!

**Comment by jperl** [comment]
Unfortunately this broke the windows tests, so I had to revert it.

```
      0 [main] dirname (6720) C:\msys64\usr\bin\dirname.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x180330408.
```

https://github.com/qawolf/qawolf/commit/b386fc50f816fe46f12981e991e323974ea72995/checks?check_suite_id=404519496

**Comment by jperl** [comment]
Nvm I think the Windows test issue is github actions related.

**Comment by jamesgeorge007** [comment]
Oh that's odd :disappointed:

**Pull request merged**
